pipeline {

	agent { label 'docker' } 
	tools {
		go 'go1.18'
	}

	environment {
		GO114MODULE = 'on'
		CGO_ENABLED = 0 
		GOPATH = "${JENKINS_HOME}/jobs/${JOB_NAME}/builds/${BUILD_ID}"
		GOCACHE = "/tmp"
	}
    
	stages {        
		stage('Pre Test') {
			steps {
				echo 'Installing dependencies'
				sh 'go version'
			}
		}
			
		stage('Build') {
			steps {
				dir('app') {
					echo 'Compiling and building'
					sh 'go build'
				}
			}
		}
	}
}
