pipeline {

	agent { label 'docker' } 
	tools {
		go 'go1.18'
	}

	environment {
		GO114MODULE = 'on'
		CGO_ENABLED = 0 
		GOPATH = "${JENKINS_HOME}/jobs/${JOB_NAME}/builds/${BUILD_ID}"
		GOCACHE = "/tmp"
	}
    
	stages {        
			
		stage('Golang Build') {
			steps {
				dir('app') {
					echo 'Compiling and building'
					sh 'go build'
				}
			}
		}

		stage('Docker Build') {
			steps {
				docker.withRegistry('https://registry.redhat.io', 'registry-redhat-io') {
					dir('app') {
					  script {
							echo 'Performing docker build'
							def customImage = docker.build("my-image:latest")
						}
					}
				}
			}
		}
	}
}
